GET  http://localhost:8080/api/v1/product
Content-Type: application/json

#########

# Login to get Bearer Token
# @name tokenAPI
POST  http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "email": "igor@email.com",
  "password": "test"
}
###

@token = {{tokenAPI.response.body.token}}
# Create product
# @name createProduct
POST http://localhost:8080/api/v1/product
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Fender Stratocaster",
  "description": "Fender Stratocaster Legitime",
  "image": "image-test",
  "quantity": 100,
  "price": 14999.99
}

###

@token = {{tokenAPI.response.body.token}}
# Create product
# @name getProductById
GET http://localhost:8080/api/v1/product/1
# Authorization: Bearer {{token}}
Content-Type: application/json
